language: python

python:
  - 2.5
  - 2.6
  - 2.7

before_install: 
  - pip install MySQL-python

branches:
  only:
    - master

before_script:
  - mysql -e 'create database curdtest;'

script: nosetests -v -x --process-timeout=10 -w tests --nocapture
