language: python

python:
  - 2.5
  - 2.6
  - 2.7

before_install: 
  - pip install MySQL-python
  - python setup.py install

branches:
  only:
    - dev
    - master

services: mysql

before_script:
  - mysql -e 'create database virgotest;'

script: nosetests -w tests
