language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install MySQL-python PyMySQL; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install MySQL-python PyMySQL; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install PyMySQL; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install PyMySQL; fi

branches:
  only:
    - master
    - dev

before_script:
  - pip install toml.py
  - mysql -e 'create database skylarktests;'

script: ./runtests.py
